Shrey mehra patch 1
hackclub/dns pull request #1018
Opened 2023-11-14 13:33 UTC by Shrey-Mehra

2023-11-21 11:09 UTC, JosiasAurel commented
please resolve conflicts

2023-11-21 14:51 UTC, grymmy requested changes

2023-11-21 14:51 UTC, grymmy commented on hackclub.com.yaml
> +
Please clean up whitespace to be consistent with the rest of the file.

2023-11-21 14:51 UTC, grymmy commented on dino.icu.yaml
> +
Please make whitespacing consistent w/ rest of file.

2023-11-27 17:37 UTC, grymmy requested changes

2023-11-27 17:37 UTC, grymmy commented on dino.icu.yaml
> +- ttl: 1
The indentation of this section looks incorrect.

2023-11-28 14:26 UTC, Muirrum requested changes
Quick fix for DNS syntax.

Also -- can you edit this PR to include a quick description of what it's for?

2023-11-28 14:26 UTC, Muirrum commented on hackclub.com.yaml
> +  domain: codethetech.hackclub.com
Octodns expects a `value` key, here's a quick fix!

```suggestion
  value: codethetech.github.io
```

2023-11-29 18:16 UTC, Muirrum requested changes

2023-11-29 18:16 UTC, Muirrum commented on hackclub.com.yaml
> +
There doesn't seem to be a github pages here, and I think this site is out-of-scope for hackclub.com, @grymmy can you chime in on scope?

2023-11-29 18:16 UTC, Muirrum commented on dino.icu.yaml
> +  value: cname.vercel-dns.com.
Please put this description in the Pull Request description!

2024-03-18 14:38 UTC, Shrey-Mehra commented
Hey @reesericci i felt i should close this pull request because it's making me too much confusing regarding process . I want this domain but closing due to confusion

2024-03-18 14:38 UTC, closed without merging

2024-03-18 14:40 UTC, reesericci commented
Like I said - please feel free to open a new PR!

2024-03-18 14:41 UTC, Shrey-Mehra commented
Sure thanks @reesericci