Add TXT Verification for northpark.hackclub.com
hackclub/dns pull request #1041
Opened 2024-01-09 03:14 UTC by AyaanT0

Added TXT verification link from Vercel to make northpark.hackclub.com point to nphack.club

2024-01-09 04:21 UTC, Muirrum requested changes

2024-01-09 04:21 UTC, Muirrum commented on hackclub.com.yaml
> +    - vc-domain-verify=northpark.hackclub.com,366fafcc48a7709aeea8
If you'd like this to point to vercel, you need to create another record for `northpark` in the appropriate spot in the file. Take a look at the README and create a `northpark` record pointing to `cname.vercel-dns.com.`

2024-01-09 04:26 UTC, AyaanT0 reviewed
Updated the file to reflect the changes

2024-01-15 20:37 UTC, Muirrum approved these changes

2024-01-26 15:29 UTC, Muirrum approved these changes

2024-02-01 16:36 UTC, closed without merging