Update the stemegypt.hackclub.com CNAME records
hackclub/dns pull request #1093
Opened 2024-02-24 18:25 UTC by Geo-sudo

Hey, vice president of the stemegypt branch for the 2024 season here! I updated the stemegypt subdomain to the new CNAME records.

2024-02-25 20:05 UTC, reesericci requested changes

2024-02-26 07:05 UTC, Geo-sudo commented on hackclub.com.yaml
>    - ttl: 1
I changed it. But why does most of the rest of the records have a low TTL too? I just noticed this and it seems weird.

2024-02-26 13:17 UTC, reesericci approved these changes
LGTM!

2024-02-26 13:18 UTC, reesericci commented on hackclub.com.yaml
>    - ttl: 1
That's something being discussed in another issue

2024-02-26 13:19 UTC, merged