adding resend records
hackclub/dns pull request #1099
Opened 2024-02-29 21:29 UTC by tobyab

adding these records so we can send adults trying to join emails about... not joining!

2024-02-29 22:16 UTC, Muirrum requested changes
please set both TTLs to 600 per README and fix MX record test fail

2024-03-02 03:00 UTC, alx-alexpark commented on hackclub.com.yaml
> +  - ttl: 1
Potential email spoofing risk?

2024-03-02 03:00 UTC, alx-alexpark commented on hackclub.com.yaml
> +    value: v=spf1 include:amazonses.com ~all
Potential email spoofing risk?

2024-03-02 03:17 UTC, closed without merging

2024-03-02 03:19 UTC, tobyab commented
Not using Resend anymore! Appreciate you both for taking the time to review this though, @Muirrum and @alx-alexpark :)