Update ttl: 1 to ttl: 600 on all things as per DNS guidelines
hackclub/dns pull request #1142
Opened 2024-04-27 00:43 UTC by jaspermayone

2024-04-27 00:43 UTC, jaspermayone commented
@grymmy this looks like a you thing to review :)

2024-04-27 00:50 UTC, alx-alexpark approved these changes
Should be OK in theory -- need confirmation from Graham.

2024-04-27 02:33 UTC, aramshiva commented
This was implemented here:
#1023
#1096

2024-04-27 16:07 UTC, northeastprince commented
You can just [set it as the default](https://github.com/octodns/octodns/blob/139e73cfd0af8cbe406bd51cdf20b10576bcd9f6/octodns/provider/yaml.py#L19-L32).

2024-04-27 17:34 UTC, alx-alexpark requested changes
Let's do what matt suggested

2024-04-28 01:20 UTC, Muirrum commented
That won't fix the records that already have an incorrect TTL set. This PR is still necessary to bring records into alignment with policy.

2024-04-28 01:40 UTC, northeastprince commented
Yeah but then you don't have to repeat the same thing for every record, you can just remove it.

2024-04-30 02:07 UTC, closed without merging

2024-04-30 18:52 UTC, jaspermayone commented
Superseded by #1149