custom email
hackclub/dns pull request #1168
Opened 2024-05-09 05:28 UTC by john-kelsey

custom email

2024-05-09 06:06 UTC, Muirrum requested changes
Hey, can you give more detail on what this PR is supposed to do?

2024-05-09 08:34 UTC, john-kelsey commented
Hi , I wanted to configure a custom email with my .hackclub.com domain for
the club , but whatever I did ,did not work , . I would really appreciate
it if you told me how to configure a custom email

On Thursday, May 9, 2024, Cara Salter ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey, can you give more detail on what this PR is supposed to do?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/dns/pull/1168#pullrequestreview-2047211913>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIAC2JT55WS5HHWJEZXLHK3ZBMG7TAVCNFSM6AAAAABHOF6L72VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANBXGIYTCOJRGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-10 13:34 UTC, Muirrum requested changes

2024-05-10 13:34 UTC, Muirrum commented on hackclub.com.yaml
> +        preference: 10
Please don't modify the root MX records
```suggestion
```

2024-05-10 13:34 UTC, Muirrum commented on hackclub.com.yaml
> +      - forward-email=johnkelsey.irungu@gmail.com
```suggestion
```

2024-05-10 13:34 UTC, Muirrum commented on hackclub.com.yaml
> +
```suggestion
  - ttl: 600
    type: MX
    values: 
      - exchange:  mx1.forwardemail.net.
        preference: 10
      - exchange:  mx2.forwardemail.net.
        preference: 10
  - ttl: 600
    type: TXT
    values:
      - forward-email=johnkelsey.irungu@gmail.com
       
```

This just modifies the TXT record's TTL and adds the required trailing dot to the exchanges

2024-05-11 22:04 UTC, closed without merging