Adding Summit Orpheus Odyssey and Atlantis!
hackclub/dns pull request #1179
Opened 2024-05-19 18:14 UTC by juni37

# Adding Summit Orpheus Odyssey and Atlantis!

## Description

Orpheus Odyssey was a project from the summit, and the atlantis is the new project that we're planning right now from ATL Meetup!

2024-05-19 18:16 UTC, juni37 commented
We can use the original Orpheus Odyssey that's already added - please ignore the new one that I've just added!

2024-05-19 18:17 UTC, Muirrum requested changes

2024-05-19 18:17 UTC, Muirrum commented on hackclub.com.yaml
> +  - ttl: 1
TTL needs to be at least 600

2024-05-19 18:17 UTC, Muirrum commented on hackclub.com.yaml
> +  ttl: 1
TTL needs to be at least 600

2024-06-04 18:51 UTC, Muirrum commented
hey @juni37, just following up on this. Is this PR still necessary?

2024-06-10 12:36 UTC, jaspermayone commented
Hey @juni37 just checking back in here :)

2024-08-16 15:14 UTC, Muirrum commented
Closing due to lack of response, feel free to reopen if you still need this!

2024-08-16 15:14 UTC, closed without merging