Update toonnongaeoy.dino.icu to my homelab.
hackclub/dns pull request #1184
Opened 2024-05-24 22:32 UTC by toonnongaeoy

# [Updating] `toonnongaeoy.dino.icu`

## Description

Change to point for my homelab to use reverse proxy to the site, since neocities won't disable ssl from this Slack Message :
https://hackclub.slack.com/archives/C06KMENGHQC/p1716588335739969

2024-05-24 22:34 UTC, alx-alexpark requested changes

2024-05-24 22:34 UTC, alx-alexpark commented on dino.icu.yaml
> +   value: retro.toonstorytime.me
CNAME records need a trailing dot (`.`)

2024-05-24 22:34 UTC, alx-alexpark commented on dino.icu.yaml
> +   value: retro.toonstorytime.me
It should be `retro.toonstorytime.me.`

2024-05-24 22:48 UTC, toonnongaeoy commented on dino.icu.yaml
> +   value: retro.toonstorytime.me
Okay.

2024-05-24 22:50 UTC, toonnongaeoy commented on dino.icu.yaml
> +   value: retro.toonstorytime.me
Fixed. @alx-alexpark

2024-05-25 04:10 UTC, alx-alexpark approved these changes
LGTM!

2024-05-25 04:10 UTC, merged