add punjabi translation domain: pa.hackclub.com
hackclub/dns pull request #1219
Opened 2024-07-09 10:29 UTC by dawoodb7869

Adding pa.hackclub.com for Punjabi Translation

2024-07-09 17:43 UTC, Muirrum requested changes

2024-07-09 17:43 UTC, Muirrum commented on hackclub.com.yaml
> +  - ttl: 1
ttl should be >= 600
```suggestion
  - ttl: 600
```

2024-07-10 22:32 UTC, Muirrum commented
Holding on this until hackclub/global#109 is merged

2024-07-11 08:35 UTC, dawoodb7869 commented
Alright

2024-08-26 08:18 UTC, dawoodb7869 commented
Alright, I guess it's done now

2024-08-30 02:19 UTC, Muirrum commented
please resolve merge conflicts

2024-09-26 16:20 UTC, Muirrum commented
@dawoodb7869 please resolve merge conflicts

2024-10-18 12:19 UTC, dawoodb7869 commented
@Muirrum I think It's done now, I am kinda bad with Conflict resolving, and also I dont see this account much hence the delay

2024-12-02 13:46 UTC, Muirrum requested changes

2024-12-02 13:46 UTC, Muirrum commented on hackclub.com.yaml
> +
```suggestion
```

2025-03-15 15:02 UTC, merged