Update hackclub.com.yaml
hackclub/dns pull request #1221
Opened 2024-07-12 06:25 UTC by tensixxx

# [Adding/Deleting/Updating] `subdomain.[hackclub.com/dino.icu/etc]`

## Description

Provide a description here of the changes, and if adding a subdomain provide a rationale & what it will be used for.

2024-07-12 10:40 UTC, Muirrum requested changes
In addition, can you give details on the purpose of this domain?

2024-07-12 10:40 UTC, Muirrum commented on hackclub.com.yaml
> +    value: 127.0.0.1.
couple things here:


```suggestion
pinetree:
  - ttl: 600
    type: A
    value: 127.0.0.1.
```

127.0.0.1 is the loopback address, what do you want this domain to point to?

2024-07-12 21:45 UTC, tensixxx commented
Dear Sir,

I will use this subdomain (pinetree.hack.com) as a school hack club's website.
I don't really know what I should do to replace the IP address.
Could you tell me what I should do?

Thanks,
Rachel
________________________________
发件人: Cara Salter ***@***.***>
发送时间: 2024年7月12日 18:41
收件人: hackclub/dns ***@***.***>
抄送: tensixxx ***@***.***>; Author ***@***.***>
主题: Re: [hackclub/dns] Update hackclub.com.yaml (PR #1221)


@Muirrum requested changes on this pull request.

In addition, can you give details on the purpose of this domain?

________________________________

In hackclub.com.yaml<https://github.com/hackclub/dns/pull/1221#discussion_r1675666497>:

> +  pinetree.hack.com:
+  - ttl: 600
+    type: A
+    value: 127.0.0.1.


couple things here:

⬇️ Suggested change

-  pinetree.hack.com:
-  - ttl: 600
-    type: A
-    value: 127.0.0.1.
+pinetree:
+  - ttl: 600
+    type: A
+    value: 127.0.0.1.


127.0.0.1 is the loopback address, what do you want this domain to point to?

—
Reply to this email directly, view it on GitHub<https://github.com/hackclub/dns/pull/1221#pullrequestreview-2174429906>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BD4GFZOQQILESAMH53PO54DZL6XERAVCNFSM6AAAAABKYJVH4WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNZUGQZDSOJQGY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-13 16:07 UTC, Muirrum commented
Hey,

On 7/12/24 5:45 PM, tensixxx wrote:
> Dear Sir,

Not a "sir".
> 
> I will use this subdomain (pinetree.hack.com) as a school hack club's 
> website.
> I don't really know what I should do to replace the IP address.
> Could you tell me what I should do?

That depends on where your website is being hosted. Is it being hosted 
on Vercel, or GitHub pages, or something else? Where does your site live?

Cheers,
Cara

2024-08-16 15:12 UTC, Muirrum commented
Following up on this

2024-08-30 12:25 UTC, closed without merging