chore(dino.icu): Add DNS records for <ajhalili2006|andreijiroh>.dino.icu
hackclub/dns pull request #1239
Opened 2024-08-13 16:36 UTC by ajhalili2006

# Adding `ajhalili2006.dino.icu` and `andreijiroh.dino.icu`

Pardon the Conventional Commits style in the patch/merge request title.

## Description

So I am adding my website (it was obvious that I use [Material for Mkdocs](https://github.com/squidfunk/mkdocs-material) under both `ajhalili2006` (my username) and `andreijiroh` (first name) subdomains. Please let me know if I should pick either one and I'll amend the commit later.

For technicalities behind the CNAME record, I'll be doing the redirects via my own Caddy config at https://github.com/recaptime-dev/proxyparty-caddy instead of setting up additional custom domains on my Cloudflare Pages project. (The Caddy server in question is hosted on an `e2-micro` GCP Compute Engine instance per https://github.com/recaptime-dev/proxyparty-caddy/blob/main/SETUP.md#gcp-compute-engine-vm.)

2024-08-15 05:36 UTC, ajhalili2006 commented
Just rebased against the main branch to keep things clean.

2024-08-30 12:24 UTC, Muirrum requested changes

2024-08-30 12:24 UTC, Muirrum commented on dino.icu.yaml
> +
delete spurious change

2024-08-31 19:13 UTC, alx-alexpark approved these changes
lGtM

2024-08-31 19:15 UTC, merged