Adding golden.hackclub.com
hackclub/dns pull request #1242
Opened 2024-08-15 02:00 UTC by kriaga259

## Description
Added Golden to hackclub.com.yaml
Golden is a Days of Service event part of the [Athena](https://athena.hackclub.com/events) intiative

2024-08-16 15:08 UTC, Muirrum requested changes
addtl -- if this is an HQ event, site should probably not be hosted on a personal github account.

2024-08-16 15:08 UTC, Muirrum commented on hackclub.com.yaml
> +    value: https://kriaga259.github.io/golden/.
DNS records can't have protocols (`https`) or paths (`/golden/`)

```suggestion
    value: kriaga259.github.io.
```

2024-08-16 16:13 UTC, revaga commented
> addtl -- if this is an HQ event, site should probably not be hosted on a personal github account. suggest migrating repository to hackclub github org

how can we migrate to the hackclub github org?

2024-08-16 16:49 UTC, alx-alexpark commented
Hi Reva 🔪!

You can use the repo creation request in the #hq-engineering channel bookmark under "Create service ticket". You can then migrate your git repo there.

2024-08-31 16:24 UTC, alx-alexpark requested changes
Hi! CNAME records cannot have a protocol or path in the record. You should assign a custom domain using the instructions [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site)!

2024-08-31 16:24 UTC, alx-alexpark commented on hackclub.com.yaml
> +    value: https://hackclub.github.io/golden/
```suggestion
    value: hackclub.github.io.
```

2024-08-31 17:20 UTC, kriaga259 commented
Hi! Is it better now?

2024-08-31 17:27 UTC, alx-alexpark requested changes
Just one last thing: when deploying site from vercel you should cname to `cname.vercel-dns.com.` instead of the hackclub.dev domain. After this you should be all good!

2024-08-31 17:27 UTC, alx-alexpark commented on hackclub.com.yaml
> +    value: golden.hackclub.dev.
```suggestion
    value: cname.vercel-dns.com.
```

2024-08-31 18:20 UTC, alx-alexpark approved these changes
yummy

2024-08-31 18:21 UTC, merged