Adding nl.hackclub.com
hackclub/dns pull request #1251
Opened 2024-08-20 10:21 UTC by Kipp-ie

# [Adding/Deleting/Updating] `subdomain.[hackclub.com/dino.icu/etc]`

## Description

Provide a description here of the changes, and if adding a subdomain provide a rationale & what it will be used for.
I made the global website in dutch. https://github.com/Kipp-ie/global

2024-08-20 18:02 UTC, Muirrum commented
Holding on hackclub/global#114

2024-08-25 20:31 UTC, maxwofford requested changes
Heads up, this isn't in alphabetical order & won't deploy! Please update so we can merge

2024-08-25 20:34 UTC, Muirrum requested changes

2024-08-25 20:34 UTC, Muirrum commented on hackclub.com.yaml
> +  value: cname.vercel-dns.com.
Remove this addtl domain from the PR

2024-09-26 16:19 UTC, Muirrum commented
hackclub/global#114 merged, @Kipp-ie please resolve review comments so this can be merged!

2025-03-15 15:03 UTC, Muirrum commented
Following up on this, is this still needed?

2025-03-23 19:37 UTC, closed without merging