[Adding] aviquo DNS
hackclub/dns pull request #1270
Opened 2024-09-01 17:19 UTC by om-raheja

This will be used to host aviquo, an extracurricular finder for high schoolers. Completely free and open source.

2024-09-01 18:15 UTC, alx-alexpark commented
Hey! Sounds like an interesting project. Is this affiliated with Hack Club? Your subdomain should be under dino.icu instead of hackclub.com.

2024-09-01 18:16 UTC, alx-alexpark commented on hackclub.com.yaml
> +    type: CNAME
```suggestion
    type: A
```
IPv4 address records should use record type A

2024-09-01 19:30 UTC, om-raheja commented
Hey, I switched the CNAME to an A record. The project isn't directly associated with hack club, but I'm a high schooler and on https://toolbox.hackclub.com, it says I can get a free hackclub.com subdomain to host some of my projects. Please let me know if any further verification is needed.

2024-09-01 20:29 UTC, om-raheja commented
I changed it to dino.icu, but I would prefer if I could have a .org or .com subdomain instead 😅 It'll do for now though, thank you!

2024-09-03 17:13 UTC, om-raheja commented
Anything else I need to add?

2024-09-03 18:03 UTC, Muirrum requested changes

2024-09-03 18:03 UTC, Muirrum commented on hackclub.com.yaml
> +
delete spurious change

2024-09-26 16:19 UTC, Muirrum commented
is this still needed?

2024-09-26 22:31 UTC, om-raheja commented
no, thank you On Sep 26, 2024, at 12:19, Cara Salter ***@***.***> wrote:﻿
is this still needed?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-09-27 11:52 UTC, closed without merging