Update hackclub.com.yaml
hackclub/dns pull request #1284
Opened 2024-09-06 01:51 UTC by AAlchi

# [Adding] `hersey.hackclub.com`

## Description

This subdomain will be used for our school's Hack Club (John Hersey High School). Eventually, it will be updated around every week to have Hack Club members go to the site.

2024-09-06 02:28 UTC, Muirrum requested changes

2024-09-06 02:28 UTC, Muirrum commented on hackclub.com.yaml
> +    value: hersey-hack-club.vercel.app/.
DNS records can't have paths `/`


```suggestion
    value: hersey-hack-club.vercel.app.
```

2024-09-07 17:26 UTC, Muirrum requested changes
please also complete subdomain verification per vercel's instructions

2024-09-07 17:26 UTC, Muirrum commented on hackclub.com.yaml
> +    value: hersey-hack-club.vercel.app.
iirc vercel's dns instructions are:

```suggestion
    value: cname.vercel-dns.com.
```

2024-09-10 00:03 UTC, AAlchi reviewed
Hello. I have made the requested changes and I don't want to rush, but I'd just like to know when to expect this to be ready. I'm good for this week, but I want to make sure that the website is up by next week. Thank you!

2024-09-10 13:18 UTC, AAlchi commented
How do I add the vercel verification record?

2024-09-26 16:18 UTC, Muirrum commented
Is this still needed

2024-09-26 21:44 UTC, AAlchi commented
I'm confused on how it's supposed to work and I'm not really sure what to do. Can you please explain it in more detail?

2024-09-27 11:52 UTC, Muirrum commented
https://github.com/hackclub/dns?tab=readme-ov-file#limitations

Your vercel verification needs to go under the root _vercel record at the top of the file.

2024-09-29 22:59 UTC, AAlchi commented
I added the change. Please lmk if there is anything else I need to do.

2024-09-29 23:33 UTC, alx-alexpark approved these changes
yum

2024-09-29 23:34 UTC, merged