Update hackclub.com.yaml for epoch0 club
hackclub/dns pull request #1305
Opened 2024-09-16 08:48 UTC by Shaileshsaravanan

# [Adding] `epoch0.hackclub.com`

## Description

This PR adds DNS records for the Epoch0 Club, enabling email verification and Vercel hosting. The addition of these records will enhance the club's digital presence and functionality.

# [Adding/Deleting/Updating] `subdomain.[hackclub.com/dino.icu/etc]`

## Description

Provide a description here of the changes, and if adding a subdomain provide a rationale & what it will be used for.

2024-09-16 12:01 UTC, Muirrum commented
What's the difference between this and #1297 ?

2024-09-16 13:26 UTC, Shaileshsaravanan commented
I had forgotten to add a cname record for vercel, now i have added it.

2024-09-16 14:46 UTC, Muirrum commented
In the future, please amend your commits to the previous pull request, either by adding new commits or force-pushing amended commits.

2024-09-16 14:46 UTC, Muirrum requested changes

2024-09-16 14:46 UTC, Muirrum commented on hackclub.com.yaml
> +      - vc-domain-verify=epoch0.hackclub.com,ff9cc22901478379593a
This needs to go in the place specified in the README.

2024-09-16 14:46 UTC, Muirrum commented on hackclub.com.yaml
> +      - zoho-verification=zb71957826.zmverify.zoho.in
remove this
```suggestion
```

2025-03-15 15:03 UTC, Muirrum commented
Following up on this, is this still needed?

2025-03-23 19:37 UTC, closed without merging