Adding `soleimani.hackclub.com`
hackclub/dns pull request #1320
Opened 2024-09-20 16:45 UTC by soleimanis

# Adding `soleimani.hackclub.com`

## Description

Hi, I hope you're having a wonderful day!

This is a showcase of Hack Club projects and accomplishments.

Thank you very much in advance.

2024-09-25 19:55 UTC, Muirrum commented
What's the difference between this and #1292 ?

2024-09-25 20:54 UTC, soleimanis commented
There is absolutely no difference. It seems I previously thought I didn't want to move forward with it and deleted and closed the pull request but I had the same idea again and forgot I had already created it.
Apologies for creating a duplicate pull request.

2024-09-26 16:17 UTC, Muirrum commented
As I said in the previous PR, personal sites are out-of-scope for hackclub.com. Please move this to dino.icu

2024-09-26 16:18 UTC, Muirrum requested changes

2024-09-26 16:18 UTC, Muirrum commented on hackclub.com.yaml
> +    value: soleimanis.github.io.
out-of-scope, please move to dino.icu

2024-09-26 17:07 UTC, soleimanis commented on hackclub.com.yaml
> +    value: soleimanis.github.io.
Will do, thank you very much

2024-09-26 17:07 UTC, closed without merging