Adding `shipping.hackclub.com`
hackclub/dns pull request #1353
Opened 2024-10-13 21:44 UTC by grandell1234

# Adding `shipping.hackclub.com`

## Description

For the new easy shipping program which allows people to easily ship and track internationally, for clubs and certain YSWS.

2024-10-13 21:46 UTC, alx-alexpark requested changes

2024-10-13 21:46 UTC, alx-alexpark commented on hackclub.com.yaml
> +    value: shipping-hq.vercel.app
🚨
```suggestion
    value: cname.vercel-dns.com.
```

2024-10-13 22:32 UTC, grandell1234 commented on hackclub.com.yaml
> +    value: shipping-hq.vercel.app
Fixed in latest push, sorry.

2024-10-14 01:58 UTC, alx-alexpark approved these changes
yum

2024-10-14 01:59 UTC, merged