Updating counterspell.hackclub.com
hackclub/dns pull request #1374
Opened 2024-10-24 22:36 UTC by slashtechno

# Updating `counterspell.hackclub.com`

## Description

Using Gmail's "Send mail as" with `<city>@counterspell.hackclub.com` results in sent emails being marked as spam due to failing DMARC.

2024-10-24 23:27 UTC, samdev-7 approved these changes

2024-10-25 00:46 UTC, alx-alexpark approved these changes
l g tm

2024-10-25 00:49 UTC, alx-alexpark requested changes
I forgot that you had to escape semicolons

2024-10-25 00:49 UTC, alx-alexpark commented on hackclub.com.yaml
> +    value: v=DMARC1; p=none; rua=mailto:dmarc@counterspell.hackclub.com
```suggestion
    value: v=DMARC1\; p=none\; rua=mailto:dmarc@counterspell.hackclub.com
```

2024-10-25 01:29 UTC, merged