Adding archives.hackclub.com
hackclub/dns pull request #1386
Opened 2024-10-29 08:29 UTC by crabby605

# Adding `archives.hackclub.com`

## Description

this subdomain will be used for storing all the leader newsletters

2024-10-29 11:18 UTC, cytronicoder commented
what does this mean?

2024-10-29 11:58 UTC, crabby605 commented
> what does this mean?

I'm trying to revive the leader newsletter archive with @jaredsene so I wanted a subdomain for it

2024-10-29 13:09 UTC, alx-alexpark requested changes
Please sort alphabetically within the file. Also, waiting on HQ approval.

2024-10-29 13:14 UTC, crabby605 commented
> Please sort alphabetically within the file. Also, waiting on HQ approval.

I need HQ approval?? I had asked Jared though?

2024-10-29 13:15 UTC, crabby605 commented
> > Please sort alphabetically within the file. Also, waiting on HQ approval.
> 
> I need HQ approval?? I had asked Jared though?

But not for the subdomain if that's something I'm not supposed to do then close this PR

2024-10-29 18:58 UTC, alx-alexpark commented
Holding, pending approval

2024-11-01 09:02 UTC, crabby605 commented
> Holding, pending approval

Approval yet?

2024-12-02 14:39 UTC, crabby605 commented on hackclub.com.yaml
> +    value: crabby605.github.io.
Still waiting on an approval!

2025-02-23 07:34 UTC, closed without merging