Update hackclub.com.yaml
hackclub/dns pull request #1452
Opened 2024-12-12 00:15 UTC by BennyGaming635

# [Adding/Deleting/Updating] `subdomain.[hackclub.com/dino.icu/etc]`

## Description

Provide a description here of the changes, and if adding a subdomain provide a rationale & what it will be used for.

2024-12-12 00:17 UTC, BennyGaming635 commented
Adding this subdomain as we're a new hack club that has had their meeting with jps. Used to advertise and also anything regarding our Hack Club.

2024-12-12 00:52 UTC, alx-alexpark requested changes
Hii!

Thanks for submitting your PR. Unfortunately, there are a few issues that need to be resolved.

Firstly, you should replace SUBDOMAIN_NAME with the subdomain that you want, like this.
```yaml
henleyhigh:
  - ttl: 600
    type: CNAME
    value: <another domain name based on where you are hosting your site>
```
The value of the CNAME is essentially a reference to the server that is hosting your website. I can't tell you what to put here, as it depends on where and how you are hosting your website. 

Finally, after you do so, please make sure to sort the record within the file so that it is in the appropriate alphabetical order.

Thanks! and feel free to DM me on slack (@alex (p variant)) if you need any help.

2025-03-15 15:08 UTC, Muirrum commented
Following up on this, is this still needed?

2025-03-15 20:24 UTC, BennyGaming635 commented
Nope

2025-03-15 20:40 UTC, closed without merging