Adding glenny.hack.club
hackclub/dns pull request #1460
Opened 2024-12-19 06:00 UTC by BobbedBob

# Adding glenny.hack.club

## Description

I am adding glenny.hack.club which points to my Github Pages site currently at ghc.bobbedbob.io.
This is for Glenny Hack Club which is an official Hack Club that will run in 2025 at Glen Waverley Secondary College, Melboburne, Australia.

2024-12-19 10:02 UTC, saumilthecode commented
i dont really maintain this but i think you updated the wrong one

hack.club is for shortlinks.
the one you want to put your club website on is the hackclub.com file > https://github.com/hackclub/dns/blob/main/hackclub.com.yaml

2024-12-19 10:15 UTC, BobbedBob commented
> i dont really maintain this but i think you updated the wrong one
> 
> hack.club is for shortlinks. the one you want to put your club website on is the hackclub.com file > https://github.com/hackclub/dns/blob/main/hackclub.com.yaml

Is there some sort of evidence to this reply? I assumed that when it says:
> ...under domains following the format hackclub.xxx(or other domains referring to hackclub), are only available for clubs...
That I can choose which kind of domain I would like to use for my club from the existing .yaml files.

2024-12-19 16:08 UTC, Muirrum commented on hack.club.yaml
> +    value: bobbedbob.github.io
Please move to hackclub.com. hack.club is reserved for internal use.

2024-12-19 16:09 UTC, Muirrum requested changes

2024-12-19 16:09 UTC, Muirrum commented on hack.club.yaml
> +    value: bobbedbob.github.io
Please move to hackclub.com, hack.club is reserved for internal use.

2024-12-20 05:04 UTC, alx-alexpark reviewed
Using gh pages generally requires a verification record, does github ask you to add one?

2024-12-20 16:46 UTC, BobbedBob commented
> Using gh pages generally requires a verification record, does github ask you to add one?

Nope, not at all.

2024-12-20 17:10 UTC, alx-alexpark approved these changes
lgtm

2024-12-20 17:12 UTC, merged