Adding 'hackerspace.hackclub.com'
hackclub/dns pull request #1461
Opened 2024-12-19 19:56 UTC by arsoninstigator

# Adding `hackerspace.hackclub.com`

## Description
Hackerspace is an after-school girls-in-tech club that's held at a local makerspace in New Delhi, India that caters towards middle-school / high-school-aged girls and nudges them in the direction of STEM/Tech and Coding. We host workshops at different skill levels, teach industry specific skills (like git), provide mentorship to beginners, hack on projects and build things with tools at hand.

We’re affiliated with Hack Club and host a lot of events focused around their programs (like high seas, boba drops, fraps etc.). We usually meet every other week on Saturday at [redacted] makerspace in South Delhi or online via Zoom. As the club leader, it's necessary to note my experience in India where women in technical classes is a rare sight, and so, I'm dedicated to the cause of making tech more accessible for young girls who may have been too intimidated to ever properly explore the field.

2024-12-19 23:16 UTC, alx-alexpark requested changes
Hii, 

Firstly, I think hackerspace is a bit too vague of a name, perhaps could you use `hackerspace-in`?

Also, a CNAME record will not work as a redirect, you should host the site on it's own domain using vercel or netlify and then cname that appropriately

2024-12-21 07:35 UTC, arsoninstigator commented
Can we not do hackerspace.hackclub.com due to any restrictions ? Otherwise these also work (but I don't know how to go about officially changing our club name (since it's connected with an HCB account / shows up on the club map). 

- hackerspacein.hackclub.com, 
- hackerspace-in.hackclub.com, 
- hackerspaceclub.hackclub.com 
- hackerspaceindia.hackclub.com 

I definitely deploy this on Vercel if necessary but I thought github-pages would be easier because it's static. But with Vercel, how would I go about getting a CNAME record for that? I'm sorry if this is too basic but I do design/hardware stuff mostly and haven't done this before without detailed instructions. When I applied for my personal dino.icu subdomain, I just used the custom domain field within github pages itself and stuck to the default CNAME in the template.

Thank you so much for your support and insights, hope you have a Joyful Christmas and a Happy New Year !

2024-12-21 18:38 UTC, alx-alexpark commented
Any of the 4 subdomains that you suggested will work with me! Your choice on which one you like the most.

I would make another repo which only has the hackerspace site, and then host that on Vercel or Netlify. Vercel or Netlify will give you specific instructions on what type of dns record you should add. Once you're ready, you can simply commit to your fork of hackclub/dns, and re-request a review.

2024-12-26 22:32 UTC, arsoninstigator commented
I like hackerspaceclub.hackclub.com and have deployed the website on vercel. I can't figure out how to find the specific DNS record for it though.

2024-12-29 05:12 UTC, alx-alexpark commented
add hackerspace.hackclub.com to your vercel deployment under domains, and add the record it tells you to. You can also find plenty of other examples using vercel in the hackclub.com.yaml file

2025-03-15 15:01 UTC, Muirrum commented
Following up on this, is this still needed?

2025-03-23 19:39 UTC, closed without merging