Add Domain for Ronald Reagan HS
hackclub/dns pull request #524
Opened 2021-07-14 03:59 UTC by Sarthak-Dayal

Add domain for Ronald Reagan High School's club website.

2021-07-14 04:41 UTC, sampoder requested changes
nice website! however, this won't work as DNS doesn't support Vercel (it's a limit on Vercel's end, we can only have HQ sites running on Vercel

2021-07-14 16:16 UTC, Sarthak-Dayal commented
Would it work if we hosted this on netlify instead?

2021-07-15 01:14 UTC, sampoder commented
yep, it would!

2021-07-23 05:27 UTC, sampoder approved these changes

2021-07-23 05:27 UTC, merged