added gaurav
hackclub/dns pull request #845
Opened 2023-03-02 06:23 UTC by yednapg

2023-03-05 10:48 UTC, sampoder commented
hey @yednapg! current policy is that `hackclub.com` domains aren't for personal usage - how about a `dino.icu` domain?

2023-03-05 10:49 UTC, sampoder requested changes
^

2023-03-05 10:57 UTC, yednapg commented
I think I've requested for `dino.icu`. Isn't @sampoder?

2023-03-05 12:03 UTC, sampoder commented
My bad! I missed that - I guess that's what happens when you review too many PRs at once.

2023-03-05 12:04 UTC, sampoder commented on dino.icu.yaml
> +  value: yednapg.vercel.app.
```suggestion
  value: cname.vercel-dns.com.
```

You'll also need to add the Vercel verification TXT record to `_vercel`

2023-03-18 14:48 UTC, yednapg commented
Hey! closing this PR, I just bought my own domain pandeygaurav.com! Thanks! 🙌

2023-03-18 14:48 UTC, closed without merging

2023-03-18 14:57 UTC, sampoder commented
hack yeah!!


On Sat, Mar 18, 2023 at 10:48 PM Gaurav Pandey ***@***.***>
wrote:

> Hey! closing this PR, I just bought my own domain pandeygaurav.com!
> Thanks! 🙌
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/dns/pull/845#issuecomment-1474870145>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJP3VRHQ3WDBV4J3R5FJE63W4XDM5ANCNFSM6AAAAAAVM6RBK4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>