Added stem-kfs.hackclub.com
hackclub/dns pull request #991
Opened 2023-10-20 21:42 UTC by Ahmedk-n

2023-11-27 17:35 UTC, grymmy requested changes
Please add a good high-level description of what the goal of this PR is.

2023-11-28 13:44 UTC, Muirrum requested changes

2023-11-28 13:44 UTC, Muirrum commented on hackclub.com.yaml
> +
There should be no protocol (https) in DNS records, maybe try something like this?

```suggestion
stem-kfs:
  - ttl: 1
    type: CNAME
    value: stem-kfs-website.vercel.app.
```

Additionally, a ttl of 1 seems to be really low -- 600 seconds (or 10 minutes) seems to be a better minimum.

2024-02-18 02:50 UTC, reesericci commented
Closing due to inactivity - feel free to resubmit once you've addressed the issues above!

2024-02-18 03:03 UTC, closed without merging